# Run the unit tests on Pull Request to main branch

name: Run unit tests

on:
  pull_request:
      branches: [ main ]

jobs:
  run_unit_tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 18
      - run: yarn install --frozen-lockfile
      - run: yarn test
      - run: yarn build:ci