# Run the unit tests on push/PR merge to main branch

name: Run unit tests

on:
  push:
    branches: [ main ]
  pull_request:
      branches: [ main ]

jobs:
  run_unit_tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/cjeckout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 18
      - run: yarn install --frozen-lockfile
      - run: yarn build:ci