# test, build, release to github & npm
# generate release notes, changelog
# bump version in package.json
# when a push happens to main branch

name: Release

on:
  push:
    branches: [ main ]

jobs:
  release:
    runs_on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
          persist-credentials: false
      - name: Setup Node v18.x
        uses: actions/setup-node@v1
        with:
          node_version: 18
      - name: Install dependencies
        run: yarn install --frozen-lockfile
        run: yarn add -D semantic-release @semantic-release/git @semantic-release/changelog
      - name: Run tests
        run: yarn test
      - name: Build
        run: yarn build
      - name: Release
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: semantic-release

